### ISSUE TITLE
can't browse explorables in safari (sec-fetch-dest HTTP header)

### ISSUE THREAD

**Issue by mreinstein** [mreinstein/substrate#13]
`server.js`  looks at the header `sec-fetch-dest` to determine whether to load `*.explorable.md` modules as javascript or html. This header is only set in chrome. Need to find another way to make this determination without relying on a chrome specific request header.

**Comment by mreinstein** [comment]
honestly i might just wait to see if safari and firefox adopt the `sec-fetch-dest` request header. It's currently marked as experimental, let's give it some time and see how it works out. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Dest

**Comment by joezimjs** [comment]
Firefox now supports sec-fetch-dest: https://blog.mozilla.org/security/2021/07/12/firefox-90-supports-fetch-metadata-request-headers/

**Comment by mreinstein** [comment]
Oh wow, that must be very recent! Thanks for the heads-up.

**Comment by joezimjs** [comment]
Yup.... just restarted my Firefox browser and now I'm on 90... so I'm not getting all those errors I reported in #22.

**Comment by mreinstein** [comment]
Yay, safari added support!
