### ISSUE TITLE
Children and stepping

### ISSUE THREAD

**Issue by marcantoupin** [mreinstein/substrate#2]
I think it'd be preferable if the _step function called children's _step recursively, rather than calling requestAnimationFrame for each element of the display graph. One of the advantages is we'd be certain of the order in which they are updated.

For this to be possible, and also to be able to reach a substrate object's children in scripts, substrate objects should have a children property. A parent property as well. Then requestAnimationFrame could easily be called only for objects at the top of the display graph

**_parseModel would change like this:**
(only the children.push... line is different. The parent would need to be passed as an argument ('thisObj') in order for this child's first _step() to not call requestAnimationFrame(). thisObj is a reference to the public object that will be returned.

```
const _parseModel = function() {
	for(let attr in model.style) {
		dom.style[attr] = model.style[attr]
	}

	model.children.forEach(function(child) {
		const c = document.createElement('div')
		dom.appendChild(c)
		children.push(substrate({ dom: c, model: child }, thisObj)
		// TODO:encapsulate this in an addChild method as I suggested, call it here to add children
	})
}
```

**_step would become this:**

```
const _step = function() {
	if(disposed)
		return

	for (let i=0,le=children.length;i<le;i++)
		children[i]._step()

	_resize()

	if (!parent) _t = requestAnimationFrame(_step)
}
```
**It'd imply that _step (or rather, "step" without the underscore) should be a publicly accesible method.**

**We'd close the function like this:**

```
const thisObj = {dispose,step,children,parent}

_parseModel()
_step()

return thisObj
```

**Comment by mreinstein** [comment]
@marcantoupin sounds reasonable. I added you as a collaborator on the project, please make the change you describe :)

**Comment by marcantoupin** [comment]
Done :)
