### ISSUE TITLE
Code Failing to Import on Firefox

### ISSUE THREAD

**Issue by joezimjs** [mreinstein/substrate#22]
When running substrate, I'm not seeing any output from the code on the pages when viewing them in Firefox. This appears to be because it's having issues importing the code correctly: 

![image](https://user-images.githubusercontent.com/1313898/126184143-b67d93c4-9eec-4cca-9807-a4d28fbc03ab.png)

Screenshot taken on http://localhost:5000/scripts/experience/carousel/carousel from the Syndi codebase

**Comment by mreinstein** [comment]
Thanks for reporting! dupe of #13

**Comment by mreinstein** [comment]
For now it's chromium based browsers only

**Comment by mreinstein** [comment]
re-opening, I didn't realize that firefox just added support for the sec-fetch-dest header.

**Comment by joezimjs** [comment]
You can close this. This was happening before I updated the browser. Now that it's updated, ***this*** isn't an issue

**Comment by mreinstein** [comment]
Whoa, so firefox is working now?

**Comment by mreinstein** [comment]
oh, just saw your comment in the other issue about visualViewport. let's use this issue for that problem. The other one is related specifically to lacking `sec-fetch-dest` support.

**Comment by joezimjs** [comment]
Yes, FF is working now. visualViewport is not related to Substrate, so that's good too. We can close this.
