### ISSUE TITLE
explorable-views- with idx over 9 are nested inside a not-explorable-wrapper

### ISSUE THREAD

**Issue by appCurious** [mreinstein/substrate#27]
**sudo example to display the nested content**
div class="not-explorable-wrapper">
  content removed for clarity
 
h3 id="slider-4">My 10th Explorable example
div id="explorable-view-10" class="explorable-view">

**expectations**
explorable-view-xx and higher would be a sibling of not-explorable-wrapper

**Comment by mreinstein** [comment]
yikes. good catch!!
